### ISSUE TITLE
can't get integration tests to pass through Markdownify

### ISSUE THREAD

**Issue by akshatpradhan** [tibastral/markdownify#13]
Hi @tibastral!

We're currently integrating Markdownify into our rails application for ComplianceChimp. 

My developer @adamico is currently facing an issue,

> I'm facing a worrying issue with markdownify. All is working fine and I've managed to style the buttons toolbar with bootstrap and fontawesome and restore the write/preview tabs. What is bothering me is I cannot seem to find out how to interact with the editor through javascript in order for the integration specs to pass... This is a blocking issue for us. I'll contact the markdownify library creator to ask if he knows how to fill in the editor contents programmatically and let you know.

What do you think? Let me know.

Cheers!
Akshat

**Comment by akshatpradhan** [comment]
closing as figured it out

**Comment by adamico** [comment]
@tibastral just in case someone stumbles upon this and wonders how I solved the issue:

``` ruby
page.execute_script(%($('.CodeMirror')[0].CodeMirror.setValue('#{foobar}')))
```
