### ISSUE TITLE
Code block support

### ISSUE THREAD

**Issue by maximmcnair** [tibastral/markdownify#2]
Would be great to have code support on this. Using syntax ```.

**Comment by tibastral** [comment]
You can already do it :) I'll show you later

**Comment by tibastral** [comment]
Have you tried to do : 

``````
<a class='btn--insert' data-prefix='```' data-suffix='```' href='javascript:void(0)'>code</a>
``````

?

**Comment by mattwilsn** [comment]
Yes this works @tibastral  however it might be nice to include some default styling to 

```
<code></code>
```

**Comment by tibastral** [comment]
True
- Thibaut

**Comment by tibastral** [comment]
Closing that for now.
