### ISSUE TITLE
Video tag inserts null

### ISSUE THREAD

**Issue by davisable** [tibastral/markdownify#7]
In your demo, click the "Video" link then hit "Cancel" on the popup dialog and it inserts "null" into the window.

Also not sure what the point of the video link is? When I inserted a Youtube link via the video tag, it just inserted the actual link I'd pasted into the textarea and did nothing else.

**Comment by tibastral** [comment]
Agreed :) It should be a lot more explained.

Videos are youtube / vimeo / dailymotion links and are only interpreted in server for now and transformed by the server into embeded videos. We should definitely do it through the js client, but didn't have the time to dive into the js rendering !

**Comment by tibastral** [comment]
I think it's solved.
