### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Mistress-Anna** [tibastral/markdownify#8]
It would be nice to see what is special syntax in a line and what isn't.
For example, when a line is a title line (with #), the whole line is bigger. If the line ends with the wrong number off #'s, one can't see it before full preview mode. In this case, maybe the #'s could have a different size or color to indicate they are special syntax and be with the title style if they are literal and not a part of the title syntax (# foo ##)

**Comment by Mistress-Anna** [comment]
An example of this approach: ![adoc-mode](https://camo.githubusercontent.com/98c5abead6c1870d8b12a5ad86fea55a55047ad3/687474703a2f2f646c2e64726f70626f782e636f6d2f752f37353738393938342f61646f632d6d6f64652e706e67)

**Comment by tibastral** [comment]
I don’t get your point here.

# I like sharps, because # is amazing, the title is :

I like sharps, because # is amazing,
so I don’t see the problem !
- Thibaut

**Comment by Mistress-Anna** [comment]
Yes, but that's not what you see that in markdownify's WYSIWYG editor. Every # is big and blue and we have no cue if it's special syntax or literal text.
![2015-07-17-123008_1028x529_scrot](https://cloud.githubusercontent.com/assets/11899334/8745395/c6afd10c-2c7f-11e5-8b32-fabd1ec879e0.png)

**Comment by Mistress-Anna** [comment]
Here's a basic mockup of how it could be different (maybe not the best way):
![2015-07-17-123008_1028x529_scrot](https://cloud.githubusercontent.com/assets/11899334/8745430/21e3b9c6-2c80-11e5-999c-2a2d349e9d35.png)

**Comment by tibastral** [comment]
Ok understood, if you want to do it as an option, I could incorpore it in the next release.

**Comment by tibastral** [comment]
Let me know if you want to do it later. For now I close that.

**Comment by Mistress-Anna** [comment]
I'm sorry but I'm not a web developer, I can't submit a patch, it was a feature request or a suggestion, as you like.
